---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus
spec:
  secretName: prometheus-tls
  duration: 2160h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8
    rotationPolicy: Always
    size: 384
  dnsNames:
    - kube-prometheus-stack-prometheus
    - kube-prometheus-stack-prometheus.observability
    - kube-prometheus-stack-prometheus.observability.svc
    - kube-prometheus-stack-prometheus.observability.svc.cluster.local
    - prometheus-operated
    - prometheus-operated.observability
    - prometheus-operated.observability.svc
    - prometheus-operated.observability.svc.cluster.local
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager
spec:
  secretName: alertmanager-tls
  duration: 2160h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8
    rotationPolicy: Always
    size: 384
  dnsNames:
    - kube-prometheus-stack-alertmanager
    - kube-prometheus-stack-alertmanager.observability
    - kube-prometheus-stack-alertmanager.observability.svc
    - kube-prometheus-stack-alertmanager.observability.svc.cluster.local
    - alertmanager-operated
    - alertmanager-operated.observability
    - alertmanager-operated.observability.svc
    - alertmanager-operated.observability.svc.cluster.local
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
