---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: alertmanager-secret
  dataFrom:
    - extract:
        key: secrets/alertmanager
    - extract:
        key: secrets/pushover
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: prometheus-secret
  dataFrom:
    - extract:
        key: secrets/prometheus
