apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-snapshot-cronjob
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
     template:
        spec:
          serviceAccountName: vault-snapshotter
          volumes:
            - name: share
              emptyDir: {}
          containers:
          - name: backup
            image: hashicorp/vault:1.18.3@sha256:8f1ba670da547c6af67be55609bd285c3ee3d8b73f88021adbfc43c82ca409e8
            imagePullPolicy: IfNotPresent
            env:
            - name: VAULT_ADDR
              value: https://vault.darkfellanetwork.com:8200
            command: ["/bin/sh", "-c"]
            args:
              - >
                SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
                export VAULT_TOKEN=$(vault write -field=token auth/kubernetes/login jwt=$SA_TOKEN role=vault-snapshotter);
                vault operator raft snapshot save /share/vault-raft.snap;
            volumeMounts:
              - name: share
                mountPath: "/share"
          - name: snapshotupload
            image: amazon/aws-cli:2.22.23@sha256:1216b6a7beefc53b7de49cb7c01a8eb64fc1769be2b4a11a6361956d8996c46d
            imagePullPolicy: IfNotPresent
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-credentials-secret
                    key: access-key-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: cloudflare-credentials-secret
                    key: secret-access-key
            command:
            - /bin/sh
            args:
            - -ec
            - |
                until [ -f /share/vault-raft.snap ]; do sleep 5; done;
                aws --endpoint-url=https://2bd80478faceecf0d53c596cd910805f.eu.r2.cloudflarestorage.com s3 cp /share/vault-raft.snap s3://backups/vault/vault_raft_$(date +"%Y%m%d_%H%M%S").snap;
            volumeMounts:
            - mountPath: /share
              name: share
          restartPolicy: OnFailure
