---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  #- ./networkpolicy.yaml
configMapGenerator:
  - name: radarr-configmap
    files:
      - pushover-notify.sh=./resources/pushover-notify.sh
  - name: radarr-gatus-ep
    options:
      labels:
        gatus.io/enabled: "true"
    files:
      - config.yaml=./resources/gatus-ep.yaml
  - name: radarr-oauth2-proxy-config
    files:
      - oauth2-proxy.cfg=./resources/oauth2-proxy.cfg
generatorOptions:
  disableNameSuffixHash: true
  annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled
