---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: prowlarr-gatus-ep
    options:
      labels:
        gatus.io/enabled: "true"
    files:
      - config.yaml=./resources/gatus-ep.yaml
  - name: prowlarr-oauth2-proxy-config
    options:
      labels:
        gatus.io/enabled: "true"
    files:
      - oauth2-proxy.cfg=./resources/oauth2-proxy.cfg
generatorOptions:
  disableNameSuffixHash: true
