---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: prometheus
spec:
  provider: vault
  secretObjects:
    - data:
      - key: client_id
        objectName: client_id
      - key: client_secret
        objectName: client_secret
      secretName: prometheus-secret
      type: Opaque
  parameters:
    roleName: prometheus
    vaultAddress: 'https://vault.darkfellanetwork.com:8200'
    objects: |
      - objectName: "oauth2-proxy.cfg"
        secretPath: "secrets/data/oauth2/prometheus"
        secretKey: "oauth2-proxy.cfg"
        filePermission: 0o444
      - objectName: "client_id"
        secretPath: "secrets/data/oauth2/prometheus"
        secretKey: "client_id"
        filePermission: 0o444
      - objectName: "client_secret"
        secretPath: "secrets/data/oauth2/prometheus"
        secretKey: "client_secret"
        filePermission: 0o444
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: alertmanager
spec:
  provider: vault
  secretObjects:
  - data:
    - key: HEARTBEAT_URL
      objectName: HEARTBEAT_URL
    - key: PUSHOVER_TOKEN
      objectName: PUSHOVER_TOKEN
    - key: PUSHOVER_USER_KEY
      objectName: PUSHOVER_USER_KEY
    secretName: alertmanager-secret
    type: Opaque
  parameters:
    roleName: alertmanager
    vaultAddress: 'https://vault.darkfellanetwork.com:8200'
    objects: |
      - objectName: "oauth2-proxy.cfg"
        secretPath: "secrets/data/alertmanager"
        secretKey: "oauth2-proxy.cfg"
        filePermission: 0o444
      - objectName: "HEARTBEAT_URL"
        secretPath: "secrets/data/alertmanager"
        secretKey: "HEARTBEAT_URL"
        filePermission: 0o444
      - objectName: "PUSHOVER_TOKEN"
        secretPath: "secrets/data/alertmanager"
        secretKey: "PUSHOVER_TOKEN"
        filePermission: 0o444
      - objectName: "PUSHOVER_USER_KEY"
        secretPath: "secrets/data/alertmanager"
        secretKey: "PUSHOVER_USER_KEY"
        filePermission: 0o444
