---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret keycloak-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "{{ .KEYCLOAK_POSTGRES_USER }}"
        POSTGRES_PASS: "{{ .KEYCLOAK_POSTGRES_PASS }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        username: "{{ .ADMIN_USERNAME }}"
        password: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: secrets/cloudnative-pg
    - extract:
        key: secrets/keycloak
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-ca-cert
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cnpg-ca-cert
    template:
      engineVersion: v2
  data:
    - secretKey: cnpg-ca.crt
      remoteRef:
        key: secrets/certificates/cnpg
        property: ca.crt
