---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-404
data:
  response.body: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>404 - Page Not Found</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        body {
          display: flex;
          justify-content: center;
          align-items: center;
          min-height: 100vh;
          background: #1a1a2e;
          overflow: hidden;
        }
        .block404 {
          position: relative;
          background-image: url(https://imgur.com/eHVyWTM.jpg);
          width: 1248px;
          height: 620px;
          max-width: 100vw;
          max-height: 100vh;
          overflow: hidden;
          cursor: pointer;
        }
        .t404 {
          position: absolute;
          width: 364px;
          height: 146px;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
          background-image: url(https://imgur.com/KPZo9YX.png);
          background-size: contain;
          background-repeat: no-repeat;
          z-index: 2;
        }
        .obj {
          width: 204px;
          height: 209px;
          position: absolute;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
          animation: animation-404 6s infinite ease-in-out;
          z-index: 1;
        }
        .obj img {
          width: 100%;
          height: 100%;
          object-fit: contain;
        }
        @keyframes animation-404 {
          0%, 100% {
            transform: translate(-50%, -50%) rotate(0);
          }
          50% {
            transform: translate(-53%, -42%) rotate(-5deg);
          }
        }
        .waves {
          position: absolute;
          width: 100%;
          height: 100%;
          background-image: url(https://imgur.com/eHVyWTM.jpg);
          filter: url("#glitch");
          z-index: 0;
        }
        svg {
          position: absolute;
          width: 0;
          height: 0;
        }
      </style>
    </head>
    <body>
      <div class="block404">
        <div class="waves"></div>
        <div class="obj">
          <img src="https://imgur.com/w0Yb4MX.png" alt="404 Object">
        </div>
        <div class="t404"></div>
        <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
          <defs>
            <filter id="glitch">
              <feTurbulence type="fractalNoise" baseFrequency="0.01 0.03" numOctaves="1" result="warp" id="turb"/>
              <feColorMatrix in="warp" result="huedturb" type="hueRotate" values="90">
                <animate attributeType="XML" attributeName="values" values="0;180;360" dur="3s" repeatCount="indefinite"/>
              </feColorMatrix>
              <feDisplacementMap xChannelSelector="R" yChannelSelector="G" scale="50" in="SourceGraphic" in2="huedturb"/>
            </filter>
          </defs>
        </svg>
      </div>
    </body>
    </html>
