---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cdi
  namespace: flux-system
spec:
  targetNamespace: cdi
  dependsOn:
    - name: kubevirt
  path: ./kubernetes/main/apps/virtualization/cdi/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
