---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret grafana-oauth-client-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        client_id: "{{ .GRAFANA_OAUTH_ID }}"
        client_secret: "{{ .GRAFANA_OAUTH_SECRET }}"
        darkfellanet-ca.crt: '{{ "{{ index . \"dragonfly-ca.crt\" }}" }}'
  dataFrom:
    - extract:
        key: secrets/grafana
  data:
    - secretKey: darkfellanet-ca.crt
      remoteRef:
        key: secrets/certificates/dragonfly
        property: ca.crt
