---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-web-client
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: flux-web-client
  dataFrom:
    - extract:
        key: flux-web-client
