---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-web
spec:
  hostnames:
    - flux.darkfellanetwork.com
  parentRefs:
    - name: internal
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - name: flux-operator
          namespace: flux-system
          port: 9080
