---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbitmanage
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 30m
  chart:
    spec:
      verify:
        provider: cosign
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: qbittorrent
      namespace: media
  values:
    controllers:
      qbitmanage:
        annotations:
          secret.reloader.stakater.com/reload: qbitmanage-secret
        type: cronjob
        cronjob:
          schedule: 0 0 * * *
          timeZone: Europe/Sofia
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1

        containers:
          app:
            image:
              repository: ghcr.io/stuffanthings/qbit_manage
              tag: v4.1.15@sha256:d0ed1f22a35b732afbd7d49410bd8dfd74bd177bf53de3fedd2fdef6397b3edc
            env:
              TZ: Europe/Sofia
              QBT_CONFIG: "/config/config.yml"
              QBT_CROSS_SEED: false
              QBT_DRY_RUN: true
              QBT_LOG_LEVEL: INFO
              QBT_RECHECK: true
              QBT_REM_ORPHANED: true
              QBT_REM_UNREGISTERED: true
              QBT_RUN: true
              QBT_SHARE_LIMITS: true
              QBT_SKIP_CLEANUP: false
              QBT_SKIP_QB_VERSION_CHECK: true
              QBT_TAG_NOHARDLINKS: true
              QBT_TAG_TRACKER_ERROR: true
              QBT_TAG_UPDATE: true
              QBT_WIDTH: 100
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
            lifecycle:
              postStart:
                exec:
                  command: ["/bin/sh", "-c", "cp /secret/config.yml /config/config.yml"]
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /app/config
          - path: /config
      config-file:
        type: secret
        name: &secret qbitmanage-secret
        globalMounts:
          - path: /secret/config.yml
            subPath: config.yml
            readOnly: true
      qbittorrent:
        existingClaim: qbittorrent-config
        globalMounts:
          - path: /qBittorrent/BT_backup
            subPath: qBittorrent/BT_backup
      media:
        type: nfs
        server: 192.168.91.40
        path: /mnt/exos20/data
        globalMounts:
          - path: /data/downloads/torrents
            subPath: downloads/torrents

    rawResources:
      secret:
        enabled: true
        apiVersion: external-secrets.io/v1beta1
        kind: ExternalSecret
        spec:
          spec:
            secretStoreRef:
              kind: ClusterSecretStore
              name: vault-backend
            target:
              name: *secret
              template:
                engineVersion: v2
                data:
                  config.yml: |
                    qbt:
                      host: https://qbittorrent.darkfellanetwork.com
                      user: "{{ "{{ .QBITTORRENT_USERNAME }}" }}"
                      pass: "{{ "{{ .QBITTORRENT_PASSWORD }}" }}"

                    settings:
                      force_auto_tmm: true
                      tracker_error_tag: issue
                      nohardlinks_tag: noHL
                      share_limits_tag: ~share_limit
                      share_limits_min_seeding_time_tag: MinSeedTimeNotReached
                      share_limits_min_num_seeds_tag: MinSeedsNotMet
                      share_limits_last_active_tag: LastActiveLimitNotReached
                      cross_seed_tag: cross-seed
                      cat_filter_completed: true
                      share_limits_filter_completed: true
                      tag_nohardlinks_filter_completed: true
                      cat_update_all: true
                      force_auto_tmm_ignore_tags: cross-seed
                      disable_qbt_default_share_limits: true

                    directory:
                      remote_dir: /data/downloads/torrents
                      root_dir: /data/downloads/torrents
                      recycle_bin: /data/downloads/torrents/.RecycleBin
                      torrents_dir: /qBittorrent/BT_backup
                      orphaned_dir: /data/downloads/torrents/orphaned_data

                    cat:
                      manual: /data/downloads/torrents/manual

                    tracker:
                      torrentleech|tleechreload:
                        tag: TorrentLeech
                        notifiarr: torrentleech
                      stackoverflow|empirehost|bgp:
                        tag: IPTorrents
                        notifiarr: iptorrents
                      speedapp:
                        tag: speedapp.io
                        notifiarr: speedapp.io
                      other:
                        tag: other

                    nohardlinks:
                      movies:
                        ignore_root_dir: true
                      movies-imported:
                        ignore_root_dir: true
                      tv:
                        ignore_root_dir: true
                      tv-imported:
                        ignore_root_dir: true
                      cross-seed:
                        ignore_root_dir: false

                    share_limits:
                      noHL_cross-seed:
                        priority: 1
                        include_all_tags:
                        - noHL
                        - cross-seed
                        categories:
                        - cross-seed
                        max_seeding_time: 10m
                        cleanup: true

                      noHL_TorrentLeech:
                        priority: 2
                        include_all_tags:
                        - noHL
                        - TorrentLeech
                        categories:
                        - movies
                        - movies-imported
                        - tv
                        - tv-imported
                        max_seeding_time: 10d
                        cleanup: true

                      noHL_speedapp.io:
                        priority: 3
                        include_all_tags:
                        - noHL
                        - speedapp.io
                        categories:
                        - movies
                        - movies-imported
                        - tv
                        - tv-imported
                        max_seeding_time: 3d
                        cleanup: true

                      noHL_IPTorrents:
                        priority: 4
                        include_all_tags:
                        - noHL
                        - IPTorrents
                        categories:
                        - movies
                        - movies-imported
                        - tv
                        - tv-imported
                        max_seeding_time: 16d
                        cleanup: true

                      TorrentLeech:
                        priority: 5
                        include_all_tags:
                        - TorrentLeech
                        categories:
                        - movies
                        - movies-imported
                        - tv
                        - tv-imported
                        max_seeding_time: 30d
                        cleanup: true

                      IPTorrents:
                        priority: 6
                        include_all_tags:
                        - IPTorrents
                        categories:
                        - movies
                        - movies-imported
                        - tv
                        - tv-imported
                        max_seeding_time: 30d
                        cleanup: true

                      speedapp.io:
                        priority: 7
                        include_all_tags:
                        - speedapp.io
                        categories:
                        - movies
                        - movies-imported
                        - tv
                        - tv-imported
                        max_seeding_time: 30d
                        cleanup: true

                      manual:
                        priority: 8
                        include_any_tags:
                        - speedapp.io
                        - IPTorrents
                        - TorrentLeech
                        categories:
                        - manual
                        max_ratio: 5
                        max_seeding_time: 30d
                        cleanup: false

                    recyclebin:
                      enabled: true
                      empty_after_x_days: 3
                      save_torrents: true
                      split_by_category: false

                    orphaned:
                      empty_after_x_days: 3
                      exclude_patterns:
                      - '**/.DS_Store'
                      - '**/Thumbs.db'
                      - '**/@eaDir'
                      - '**/*.!qB'
                      - '**/*_unpackerred'
                      - '**/manual/*'
                      max_orphaned_files_to_delete: 50
            dataFrom:
              - extract:
                  key: secrets/qbittorrent
