apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls
spec:
  dnsNames:
    - plex.darkfellanetwork.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: zerossl-prod
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 384
  secretName: plex-tls
  usages:
    - digital signature
    - key encipherment
  keystores:
    pkcs12:
      create: true
      profile: Modern2023
      passwordSecretRef:
        name: *secret
        key: PKCS12_PASSWORD
