---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./certificate.yaml
configMapGenerator:
  - name: plex-loki-rules
    files:
      - plex.yaml=./resources/lokirule.yaml
    options:
      labels:
        loki_rule: "true"
  - name: plex-gatus-ep
    options:
      labels:
        gatus.io/enabled: "true"
    files:
      - config.yaml=./resources/gatus-ep.yaml
generatorOptions:
  disableNameSuffixHash: true
