---
# yaml-language-server: $schema=https://raw.githubusercontent.com/crowdsecurity/helm-charts/main/charts/crowdsec/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
spec:
  interval: 30m
  chart:
    spec:
      chart: crowdsec
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    config:

      #profiles.yaml: |
        #name: default_ip_remediation
          #debug: true
          #filters:
          #- Alert.Remediation == true && Alert.GetScope() == "Ip"
          #decisions:
          #- type: ban
            #duration: 4h
          #duration_expr: Sprintf('%dh', (GetDecisionsCount(Alert.GetValue()) + 1) * 4)
          #notifications:
            #- pushover
          #on_success: break
          #---
          #name: default_range_remediation
          #debug: true
          #filters:
          #- Alert.Remediation == true && Alert.GetScope() == "Range"
          #decisions:
          #- type: ban
            #duration: 4h
          #duration_expr: Sprintf('%dh', (GetDecisionsCount(Alert.GetValue()) + 1) * 4)
          #notifications:
            #- pushover
          #on_success: break

      #notifications:
        #http.yaml: |
          #type: http
          #name: pushover

          #log_level: info

          #group_wait: "30s"
          #group_threshold: 10
          #max_retry: 5
          #timeout: "10s"

          #-------------------------
          # plugin-specific options

          # The following template receives a list of models.Alert objects
          # The output goes in the http request body
          #format: |
            #{
            #"token": $$CROWDSEC_PUSHOVER_TOKEN,
            #"user": $$PUSHOVER_USER_KEY,
            #"message": "{{`{{range . -}}{{$alert := . -}}{{range .Decisions -}}<b>{{.Value}}</b> will get <b>{{.Type}}</b> for the next <b>{{.Duration}}</b> for triggering <b>{{.Scenario}}</b>.\r\n https://www.shodan.io/host/{{.Value}}{{end -}}{{end -}}`}}",
            #"html": "1",
            #"title": "Scenario triggered on IDS/IPS !"
            #}
          #url: https://api.pushover.net/1/messages.json
          #method: POST
          #headers:
            #Content-Type: "application/json"

      config.yaml.local: |
        db_config:
          type:     postgresql
          user:     $${DB_USER}
          password: $${DB_PASSWORD}
          db_name:  crowdsec
          host:     postgres17-rw.database.svc.cluster.local
          port:     5432
          sslmode:  require

    container_runtime: containerd

    agent:
      wait_for_lapi:
        image:
          tag: "1.37.0@sha256:768e5c6f5cb6db0794eec98dc7a967f40631746c32232b78a3105fb946f3ab83"

      acquisition:
        - namespace: network
          podName: nginx-external-controller-*
          program: nginx

        - namespace: media
          podName: jellyseerr-*
          program: jellyseerr

        - namespace: vaultwarden
          podName: vaultwarden-*
          program: VAULTWARDEN

        - namespace: idp
          podName: keycloak-0
          program: keycloak

      env:
        - name: LOCAL_API_URL
          value: "https://crowdsec-api.${PUBLIC_DOMAIN}"

        - name: PARSERS
          value: "crowdsecurity/cri-logs crowdsecurity/whitelists crowdsecurity/geoip-enrich"

        - name: COLLECTIONS
          value: "crowdsecurity/modsecurity inherent-io/keycloak LePresidente/jellyseerr crowdsecurity/nginx Dominic-Wagner/vaultwarden crowdsecurity/base-http-scenarios crowdsecurity/http-cve crowdsecurity/http-dos crowdsecurity/whitelist-good-actors"

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

    lapi:
      deployAnnotations:
        reloader.stakater.com/auto: "true"

      extraInitContainers:
        - name: initdb
          image: "ghcr.io/onedr0p/postgres-init:16.5@sha256:53fa938cfe6d2dae23b120145362341950f1154bf9d0e7f2ec4e471d61624f79"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: &secret crowdsec-secret

      persistentVolume:
        data:
          enabled: false
        config:
          enabled: false

      storeCAPICredentialsInSecret: true

      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          external-dns.alpha.kubernetes.io/target: internal.${PUBLIC_DOMAIN}
          cert-manager.io/cluster-issuer: zerossl-prod
        ingressClassName: internal
        host: &host "crowdsec-api.${PUBLIC_DOMAIN}"
        tls:
          - hosts:
            - *host
            secretName: crowdsec-tls

      env:
        - name: CROWDSEC_PUSHOVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: *secret
              key: CROWDSEC_PUSHOVER_TOKEN

        - name: PUSHOVER_USER_KEY
          valueFrom:
            secretKeyRef:
              name: *secret
              key: PUSHOVER_USER_KEY

        - name: DISABLE_ONLINE_API
          value: "false"

        - name: ENROLL_KEY
          valueFrom:
            secretKeyRef:
              name: *secret
              key: ENROLL_KEY

        - name: ENROLL_INSTANCE_NAME
          value: "cluster"

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: *secret
              key: INIT_POSTGRES_PASS

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: *secret
              key: INIT_POSTGRES_USER

        - name: BOUNCER_KEY_NGINX_EXTERNAL
          valueFrom:
            secretKeyRef:
              name: *secret
              key: BOUNCER_KEY_NGINX_EXTERNAL

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
