---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret sonarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        SONARR__AUTH__APIKEY: "{{ .SONARR_API_KEY }}"
        SONARR__POSTGRES__HOST: &dbHost postgres17-rw.database.svc.cluster.local
        SONARR__POSTGRES__PORT: "5432"
        SONARR__POSTGRES__USER: &dbUser "{{ .SONARR_POSTGRES_USER }}"
        SONARR__POSTGRES__PASSWORD: &dbPass "{{ .SONARR_POSTGRES_PASS }}"
        SONARR__POSTGRES__MAINDB: &dbName sonarr
        PUSHOVER_TOKEN: "{{ .SONARR_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        COOKIE_SECRET: "{{ .COOKIE_SECRET }}"
        CLIENT_SECRET: "{{ .CLIENT_SECRET}}"
        CLIENT_ID: "{{ .CLIENT_ID }}"
        DRAGONFLY_PASSWORD: "{{ .DRAGONFLY__PASSWORD }}"
        dragonfly-ca.crt: '{{ index . "dragonfly-ca.crt" }}'
  dataFrom:
    - extract:
        key: api-keys
    - extract:
        key: cloudnative-pg
    - extract:
        key: pushover
    - extract:
        key: secrets/oauth2/sonarr
    - extract:
        key: secrets/dragonfly
  data:
    - secretKey: dragonfly-ca.crt
      remoteRef:
        key: secrets/certificates/dragonfly
        property: ca.crt
