---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: hashicorp-vault
  target:
    name: seerr-secret
  dataFrom:
    - extract:
        key: secrets/seerr
    - extract:
        key: secrets/certificates/postgres
