---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./cluster.yaml
  - ./database.yaml
  - ./object-store.yaml
  - ./pushsecret.yaml
  - ./scheduledbackup.yaml
  - ./prometheusrule.yaml
  - ./podmonitor.yaml
