---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret bazarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        POSTGRES_USER: "{{ .BAZARR_POSTGRES_USER }}"
        POSTGRES_PASS: "{{ .BAZARR_POSTGRES_PASS }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        COOKIE_SECRET: "{{ .COOKIE_SECRET }}"
        CLIENT_SECRET: "{{ .CLIENT_SECRET}}"
        CLIENT_ID: "{{ .CLIENT_ID }}"
        REDIS_PASSWORD: "{{ .REDIS_PASSWORD }}"
        DRAGONFLY_PASSWORD: "{{ .DRAGONFLY__PASSWORD }}"
  dataFrom:
    - extract:
        key: secrets/plex
    - extract:
        key: secrets/cloudnative-pg
    - extract:
        key: secrets/api-keys
    - extract:
        key: secrets/oauth2/bazarr
    - extract:
        key: secrets/redis
    - extract:
        key: secrets/dragonfly
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret bazarr-gatus-ep
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      metadata:
        labels:
          gatus.io/enabled: "true"
      engineVersion: v2
      data:
        config.yaml: |
          endpoints:
            - name: "Bazarr"
              group: guarded
              url: "https://bazarr.darkfellanetwork.com/api/system/status"
              interval: 1m
              ui:
                hide-hostname: true
                hide-url: true
              client:
                dns-resolver: tcp://172.17.0.10:53
              conditions:
                - "[STATUS] == 200"
                - "[BODY].data.bazarr_directory == /app/bin"
              alerts:
                - type: pushover
              headers:
                X-API-KEY: {{ .BAZARR_API_KEY }}
  dataFrom:
    - extract:
        key: secrets/api-keys
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret dragonfly-ca-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
  data:
    - secretKey: dragonfly-ca.crt
      remoteRef:
        key: secrets/certificates/dragonfly
        property: ca.crt
