---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: bazarr-scripts
    files:
      - subcleaner.sh=./resources/subcleaner.sh
  - name: connectionpool
    files:
      - connectionpool.py=./resources/connectionpool.py
  - name: bazarr-oauth2-proxy-config
    files:
      - oauth2-proxy.cfg=./resources/oauth2-proxy.cfg
generatorOptions:
  disableNameSuffixHash: true
