---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sops-age-secret
stringData:
  age.agekey: ENC[AES256_GCM,data:hHup+dFxDjW9ci4cKhkxl4DSfIT7CK08HgfeQ+lce5SeeIn6unWM2LXcIA5mkwZGoLOzngAKopwt5aeThWvsLy66Q/XFp0mDHus=,iv:U4CxsaosLMXFngGGWSnutE2GHiUWKxkBDho10AtGsFQ=,tag:3PBqK9ZCbvB89b3rbgv3qw==,type:str]
sops:
  age:
    - recipient: age1frhtpr8u3u99pvcuq5mjevxdq9agjfpkd8fjtnpj9qymzh5v845q53f37d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYTBhNTk0Ni9QMHEyYldK
        cW1zUXV2c0kzNXovMjVxU2ZGWVJLcTJtYWpzCjMxWTk4UnluYVA2VGJNZXdzcjVS
        OVZCVXJrWVI1aUhDY0M3YW16Y21qQUUKLS0tIHZaTXBldGNYWVkyemlWOTJQaEdw
        azE3ZDJMZW5vdkZaUXBkNTN5MFhGS00KUYM+zFG0a0sej18dQCAS6AkCVd8FrHZp
        Lq99sdhQ86xPTIPq2MzxATsPKWM3qOiVUG3lehlF7WKe0YTAAHC3/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-04T21:40:22Z"
  mac: ENC[AES256_GCM,data:9vm2tHZHct4hLoEUg2m3qNn+spISMEyutub6GxaWRFu7q6KWU2ha444sT0Kxkp+Qq5+YnI54hBVl6yfUUVNzOnTg3D91GTatw+NM7nBI0XyiDSs0aoe3jhU+6GGepAo/Mzqra4EevFWUeLtvuCj9Pg8YtXN2C+XzBSzl0nCAC+U=,iv:aldz4a0JZlhlKQQGDq7dEsZ1tD/r8ftxUDJuVV9tgz4=,tag:3/RyEEEgF8KOn/MW7nVCHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
