---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zerossl-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: zerossl-credentials
    template:
      engineVersion: v2
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: secrets/cloudflare
        property: CF_API_TOKEN
    - secretKey: EAB_KID
      remoteRef:
        key: secrets/zerossl
        property: EAB_KID
    - secretKey: EAB_HMAC_KEY
      remoteRef:
        key: secrets/zerossl
        property: EAB_HMAC_KEY
