---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret vaultwarden-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        ADMIN_TOKEN: "{{ .VAULTWARDEN_ADMIN_TOKEN }}"
        DATABASE_URL: "{{ .VAULTWARDEN_DATABASE_URI }}"
        SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_VAULTWARDEN_PASS }}"
        SMTP_SENDER: "{{ .SMTP_SENDER }}"
        INIT_POSTGRES_DBNAME: vaultwarden
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .VAULTWARDEN_POSTGRESS_USER }}"
        INIT_POSTGRES_PASS: "{{ .VAULTWARDEN_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        PUSH_INSTALLATION_ID: "{{ .VAULTWARDEN_INSTALLATION_ID }}"
        PUSH_INSTALLATION_KEY: "{{ .VAULTWARDEN_INSTALLATION_KEY }}"
  dataFrom:
    - extract:
        key: secrets/vaultwarden
    - extract:
        key: secrets/Brevo
    - extract:
        key: secrets/cloudnative-pg
