apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    AWS_ACCESS_KEY: ENC[AES256_GCM,data:mPJ9xbM54GP9BkhOz/O7qaPsFk0=,iv:7SQQ2S89d7c0lVoxQP0JvbmpxELA8DXSYfCxaLBDF4I=,tag:tLQ/IVx6Dxuuq+K+I1vKhw==,type:str]
    AWS_SECRET_KEY: ENC[AES256_GCM,data:+acohLCugLGUY6iMpS7dVjMbMag4teGImMfC35MlQIvvpmY1HdhUqw==,iv:JzSTxol9vwjDbnihICmD5pkDazoX3GGdnNnCJzvaMdo=,tag:vaZvofDsjoPGE/G+1XPZ7Q==,type:str]
    AWS_KEY_ID: ENC[AES256_GCM,data:hLSFvhsaOzZF/2kEMKwD7bsk5QZTy2VAdDZcgRGDHjGjkQJFdVjsAROCV8T9pZ6ZuraCOjsGrBfq2/ZQ3+vYDOlKrTWBZh5DtlI4,iv:eDBs/XH6km+nOLuQ5ct1CnBPyObzgG9AA7zhsjcrES4=,tag:cW+ANHpGEbObt5wiPzIwJw==,type:str]
    CF_ACCESS_KEY_ID: ENC[AES256_GCM,data:gSFGMt/b/wgz8u1CmXtYmEWNTLmhMCMw+eZJ1JM6+FA=,iv:x5FVvz5pJh4YDIiMxRc2lGO2F9fCuZLGy5FaJOUe8OE=,tag:TBR4Cbiwl7S8S1lwWNACIw==,type:str]
    CF_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+UuNk+G8bxLEp6aPf6LsSEGQVCJFXeJ9U5bHPJ4BKzevuD04YZFbcOKm+BRW0H291RzUAl2Tj9/Bvbf2CBbf/w==,iv:XT6o5g72wZNfEj5iCFn7ZEuIwgEV3UNfolrv6VbmNN0=,tag:GhpUm3O8EqEQwA3UTMtyDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1frhtpr8u3u99pvcuq5mjevxdq9agjfpkd8fjtnpj9qymzh5v845q53f37d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T0RNbStKa0ttS3RiUk03
            WStycVN4dmhvUDBUT1o2a1R6Qnd5dkVPVFQ0ClozTS82RmlCc2o4TEQ2UGRoOGp3
            TDIxeGZHNSt1VHpGVkMweXA0RW5nY2sKLS0tIFJMeGMvWVdyRkpaVlMwa3ZBQis4
            QW1lVW5BaVpDR1JReEI2L3k1WGxwRW8KcjNPmPf05RKize92JHHw3qcWT3j5H7gE
            089qhWDhyldAZJAjJVK+6MJvFQj3JeCHHyAgfFsnhSWYBBoSCU48IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T06:19:31Z"
    mac: ENC[AES256_GCM,data:DiZhG+zeq3/V0y8fWzapBPZh5yadLiao+GDGrc8rekwwiCgW5RruZtUFsUky8bBVnYenA6uyn5W01td7L5WKbSA+q+GoltY+UKzDnsOqlGBP4oGq2l8+cpcrwA8ilQ+ZwdiVozESBVkoLhS4lpOPPIf2NqPuapsUC86STMUU+WQ=,iv:7pJL0fRm/RA/38dY9K/EBOD1wEJYeubndAUl/qQpoC0=,tag:l2A29JemexFp8bZSwqzkHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.3
