---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./certificate.yaml
  - ./helmrelease.yaml
  - ./networkpolicy.yaml
  #- ./volsync-src.yaml
  - ./vault.secret.sops.yaml
configMapGenerator:
  - name: vault-gatus-ep
    options:
      labels:
        gatus.io/enabled: "true"
    files:
      - config.yaml=./resources/gatus-ep.yaml
generatorOptions:
  disableNameSuffixHash: true
