---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./jetstack.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./nvidia-device-plugin.yaml
  - ./ingress-nginx.yaml
  - ./vault.yaml
  - ./oauth2-proxy.yaml
  - ./zfs-localpv.yaml
  - ./secrets-store-csi-driver.yaml
  - ./controlplaneio.yaml
