---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kubevirt-manager
  namespace: flux-system
spec:
  targetNamespace: kubevirt-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kubevirt
    - name: cdi
  path: ./kubernetes/main/apps/virtualization/kubevirt-manager/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
