---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: artifactory-tls-backend
spec:
  endpoints:
    - fqdn:
        hostname: artifactory.artifactory.svc.cluster.local
        port: 8082
  tls:
    insecureSkipVerify: true
