---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevirt-manager
  namespace: kubevirt-manager
spec:
  template:
    spec:
      volumes:
        - configMap:
            defaultMode: 420
            name: kubevirt-manager-oauth2-proxy-config
          name: oauth2-proxy-config
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1-amd64@sha256:95f2002754cb0f1c1553aed56f4d6564a5b860e01baccb4e1b8311ffa25c167c
          args: ["--config=/etc/oauth2-proxy.cfg"]
          ports:
            - containerPort: 4180
              name: oauth-proxy
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: CLIENT_ID
                  name: alertmanager-oauth-secret
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: CLIENT_SECRET
                  name: alertmanager-oauth-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  key: COOKIE_SECRET
                  name: alertmanager-oauth-secret
            - name: OAUTH2_PROXY_REDIS_CONNECTION_URL
              value: redis://redis-master.database.svc.cluster.local:6379/5
            - name: OAUTH2_PROXY_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: REDIS_PASSWORD
                  name: alertmanager-oauth-secret
            - name: OAUTH2_PROXY_SESSION_STORE_TYPE
              value: redis
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 2000
            runAsUser: 2000
          volumeMounts:
            - mountPath: /etc/oauth2-proxy.cfg
              name: oauth2-proxy-config
              readOnly: true
              subPath: oauth2-proxy.cfg
---
apiVersion: v1
kind: Service
metadata:
  name: kubevirt-manager
  namespace: kubevirt-manager
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    app: kubevirt-manager
  sessionAffinity: None
  type: ClusterIP
