---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-mtls
spec:
  secretName: grafana-mtls
  duration: 90d
  renewBefore: 30d
  commonName: grafana-instance
  usages:
    - client auth
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: cert-manager.io
