---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-mtls
spec:
  secretName: grafana-mtls
  duration: 2160h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8
    rotationPolicy: Always
    size: 384
  commonName: grafana-instance
  usages:
    - client auth
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: cert-manager.io
