---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    grafana.internal/instance: grafana
spec:
  config:
    auth:
      disable_login_form: "false"
    auth.generic_oauth:
      name: Keycloak-OAuth
      enabled: "true"
      use_refresh_token: "true"
      email_attribute_path: email
      login_attribute_path: preferred_username
      name_attribute_path: name
      client_id: "46f5398b-91b2-4706-bfc3-5f2f4ad624fc"
      client_secret: "$__file{/etc/secrets/oauth/client_secret}"
      scopes: "openid profile email"
      auth_url: "https://accounts.darkfellanetwork.com/realms/DarkfellaNET/protocol/openid-connect/auth"
      token_url: "https://accounts.darkfellanetwork.com/realms/DarkfellaNET/protocol/openid-connect/token"
      api_url: "https://accounts.darkfellanetwork.com/realms/DarkfellaNET/protocol/openid-connect/userinfo"
      signout_redirect_url: "https://accounts.darkfellanetwork.com/realms/DarkfellaNET/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2Fgrafana.darkfellanetwork.com%2Flogin"
      role_attribute_path: contains(resource_access."46f5398b-91b2-4706-bfc3-5f2f4ad624fc".roles[*], 'admin') && 'Admin' || contains(resource_access."46f5398b-91b2-4706-bfc3-5f2f4ad624fc".roles[*], 'editor') && 'Editor' || 'Viewer'
      role_attribute_strict: "true"
      auto_login: "true"
      allow_sign_up: "true"
      allow_assign_grafana_admin: "true"
      use_pkce: "true"
      skip_org_role_sync: "false"
    users:
      auto_assign_org: "true"
      auto_assign_org_role: Viewer
      auto_assign_org_id: "1"
    security:
      #disable_initial_admin_creation: "true"
      allow_embedding: "false"
      cookie_secure: "true"
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      reporting_enabled: "false"
      feedback_links_enabled: "false"
    auth.anonymous:
      enabled: "true"
    auth.basic:
      enabled: "false"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    log:
      mode: console
    metrics:
      enabled: "true"
    server:
      enable_gzip: "true"
      root_url: https://grafana.darkfellanetwork.com
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-secret
                      key: GF_SECURITY_ADMIN_PASSWORD
              volumeMounts:
                - name: oauth-client-secret
                  mountPath: /etc/secrets/oauth
                  readOnly: true
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: ["ALL"]}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            fsGroup: 65532
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
            - name: oauth-client-secret
              secret:
                secretName: grafana-secret
                defaultMode: 0440
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: openebs-zfs-128k
  disableDefaultSecurityContext: All
