---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dragonfly-operator
spec:
  secretName: dragonfly-operator-tls
  duration: 2160h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8
    rotationPolicy: Always
    size: 384
  dnsNames:
    - dragonfly-operator
    - dragonfly-operator.database
    - dragonfly-operator.database.svc
    - dragonfly-operator.database.svc.cluster.local
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: cert-manager.io
