---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./certificate.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: alertmanager-oauth2-proxy-config
    files:
      - oauth2-proxy.cfg=./resources/oauth2-proxy.cfg
generatorOptions:
  disableNameSuffixHash: true
