<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="
    default-src 'none';
    img-src 'self' https://static.${PUBLIC_DOMAIN}/502-service-unavailable.png;
    style-src 'unsafe-inline';">
    <title>Service Unavailable</title>
    <style>
        body {
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f8f8f8;
        }
        img {
            max-width: 100%;
            height: auto;
        }
    </style>
</head>
<body>
    <img src="https://static.${PUBLIC_DOMAIN}/503-service-unavailable.png" alt="503 Error Image">
</body>
</html>
