---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      multus:
        serviceAccount:
          identifier: multus
        type: daemonset
        initContainers:
          install-multus-binary:
            image:
              repository: ghcr.io/d4rkfella/multus-cni
              tag: 4.2.3@sha256:e15b0b9c93edbfdd01561398a623a9c108634bd8acddb6a99d1196853348c06b
            command: ["/install_multus"]
            args:
              - --type
              - thin
            securityContext:
              privileged: true
            terminationMessagePolicy: FallbackToLogsOnError
          install-cni-plugins:
            image:
              repository: ghcr.io/d4rkfella/cni-plugins-install
              tag: 1.0.3@sha256:2ea904a75bebc7aca385d029b18e3bc1e114d02bc9d71062fdde57b6b26e410e
            env:
              # renovate: datasource=github-releases depName=containernetworking/plugins
              CNI_PLUGINS_VERSION: v1.8.0
        containers:
          multus:
            image:
              repository: ghcr.io/d4rkfella/multus-cni
              tag: 4.2.3@sha256:e15b0b9c93edbfdd01561398a623a9c108634bd8acddb6a99d1196853348c06b
            args:
              - --multus-conf-file=auto
              - --multus-autoconfig-dir=/host/etc/cni/net.d
              - --cni-conf-dir=/host/etc/cni/net.d
              - --cleanup-config-on-exit=true
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 50Mi
            securityContext:
              privileged: true
            terminationMessagePolicy: FallbackToLogsOnError

    defaultPodOptions:
      hostNetwork: true
      terminationGracePeriodSeconds: 15
      dnsPolicy: "Default"

    persistence:
      cni:
        type: hostPath
        hostPath: /etc/cni/net.d
        advancedMounts:
          multus:
            multus:
              - path: /host/etc/cni/net.d
      cnibin:
        type: hostPath
        hostPath: /opt/cni/bin
        advancedMounts:
          multus:
            install-multus-binary:
              - path: /host/opt/cni/bin
                mountPropagation: Bidirectional
            multus:
              - path: /host/opt/cni/bin
            install-cni-plugins:
              - path: /host/opt/cni/bin
      tmp:
        type: emptyDir
        advancedMounts:
          multus:
            install-cni-plugins:
              - path: /tmp

    serviceAccount:
      multus: {}
