---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      uninstall:
        type: job

        annotations:
          # This is what defines this resource as a hook. Without this line, the
          # job is considered part of the release.
          helm.sh/hook: pre-delete, pre-upgrade
          helm.sh/hook-weight: "-5"
          helm.sh/hook-delete-policy: hook-succeeded

        pod:
          hostNetwork: true

        containers:
          uninstall:
            image:
              repository: docker.io/library/alpine
              tag: "3.21"

            command:
              - /bin/sh
              - -c

            args:
              - |
                set -x
                rm -rf /host/etc/cni/net.d/*multus*
                rm -rf /host/opt/cni/bin/*multus*

      multus:
        type: daemonset

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          hostNetwork: true

        initContainers:
          cni-plugins-install:
            image:
              repository: ghcr.io/d4rkfella/install-cni-bundle
              tag: v1.6.2@sha256:e9f4cb5dee7a448b4367b513056be784fed5751cc36fb7a677aa140b320afb6c

        containers:
          multus:
            image:
              repository: ghcr.io/k8snetworkplumbingwg/multus-cni
              tag: v4.1.4
            command:
              - /thin_entrypoint
            args:
              - --multus-conf-file=/config/00-multus.conf
              - --cni-bin-dir=/opt/cni/bin
              - --cni-conf-dir=/etc/cni/net.d
            resources:
              requests:
                cpu: "10m"
              limits:
                memory: "512Mi"
            securityContext:
              privileged: true

    persistence:
      config:
        type: configMap
        name: multus-configmap
        advancedMounts:
          multus:
            multus:
              - path: /config/00-multus.conf
                subPath: 00-multus.conf
                readOnly: true
      etc-cni-net-d:
        type: hostPath
        hostPath: /etc/cni/net.d
        advancedMounts:
          multus:
            multus:
              - path: /etc/cni/net.d
          uninstall:
            uninstall:
              - path: /host/etc/cni/net.d
      opt-cni-bin:
        type: hostPath
        hostPath: /opt/cni/bin
        advancedMounts:
          multus:
            cni-plugins-install:
              - path: /host/opt/cni/bin
            multus:
              - path: /opt/cni/bin
          uninstall:
            uninstall:
              - path: /host/opt/cni/bin

    serviceAccount:
      create: true
      name: multus
