apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: datavol-dest
  namespace: media
spec:
  trigger:
    manual: restore-once
  restic:
    repository: qbittorrent-volsync-secret
    destinationPVC: qbittorrent-config
    copyMethod: Snapshot
    storageClassName: openebs-zfs-128k
    moverSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
