---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: win-2k25
  namespace: flux-system
spec:
  targetNamespace: virtualization
  dependsOn:
    - name: kubevirt
    - name: cdi
  path: ./kubernetes/main/apps/virtualization/virtual-machines/win-2k25/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 5m
